/*1*/

CREATE TABLE Customer
  (CUST_ID VARCHAR2(10),
   CUS_ADDRESS VARCHAR2(35),
   CUS_CITY VARCHAR2(35),
   CUS_STATE CHAR(2),
   CUS_ZIP CHAR(5),
   CUZ_EMAIL VARCHAR2(35),
   PRIMARY KEY(CUST_ID));
 
/* 2 */  
INSERT INTO Customer VALUES(10001,'110 BLAZING ST','STJOE','MO','64506','CUS1@EMAIL.COM');
INSERT INTO Customer VALUES(10002,'120 26 ST','ST JOE','MO','64506','CUS2@EMAIL.COM');
INSERT INTO Customer VALUES(10003,'130 DOWNS RD','ST JOE','MO','64501','CUS3@EMAIL.COM');
INSERT INTO Customer VALUES(10004,'140 DONNET ST','ST JOE','MO','64506','CUS4@EMAIL.COM');
INSERT INTO Customer VALUES(10005,'150 BROWN ST','ST JOE','MO','64506','CUS5@EMAIL.COM');
INSERT INTO Customer VALUES(10006,'160 REMMY ST','ST JOE','MO','64508','CUS6@EMAIL.COM');

/* 3 */
ALTER TABLE BOOKS
  ADD PRIMARY KEY (B_CODE);


CREATE TABLE Sales_Detail
  (SALE_ID CHAR(5),
   SALE_NBR CHAR(10),
   B_CODE VARCHAR2(26),
   SS_NBR_PURCHASED NUMBER(3),
   LINE_TOTAL NUMBER(7,2),
   PRIMARY KEY(SALE_ID,SALE_NBR),
   FOREIGN KEY(B_CODE) REFERENCES BOOKS(B_CODE));
 
/*4*/ 
INSERT INTO SALES_DETAIL VALUES('10000','1','0180','1',NULL);
INSERT INTO SALES_DETAIL VALUES('10001','2','0200','2',NULL);
INSERT INTO SALES_DETAIL VALUES('10002','3','2908','3',NULL);
/*5*/ 
/*ALTER TABLE BOOKS
  ADD PRIMARY KEY(B_CODE);*/

ALTER TABLE AUTHORS
  ADD PRIMARY KEY(ID);
  
ALTER TABLE BOOKS_AUTHORS
  ADD FOREIGN KEY(BOOK_CODE) REFERENCES BOOKS(B_CODE);
  
ALTER TABLE BOOKS_AUTHORS
  ADD FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID);
 
ALTER TABLE BRANCHES
  ADD PRIMARY KEY(BRANCH);
  
ALTER TABLE BOOKS_BRANCHES
  ADD FOREIGN KEY(B_CODE) REFERENCES BOOKS(B_CODE);
  
ALTER TABLE BOOKS_BRANCHES
  ADD FOREIGN KEY(BRANCH) REFERENCES BRANCHES(BRANCH);
/*6*/ 
UPDATE BOOKS
  SET PRICE = PRICE + (.10 * PRICE)
  WHERE PUBLISHER_CODE = 'BB';

/*7*/ 

UPDATE BOOKS_BRANCHES
  SET REORDER_LEVEL = REORDER_LEVEL + 2
  WHERE REORDER_LEVEL <= 3 ;
  
/*8*/

UPDATE SALES_DETAIL
  SET LINE_TOTAL = 8.42 * SS_NBR_PURCHASED
    WHERE SALE_ID = '10000';

UPDATE SALES_DETAIL
  SET LINE_TOTAL = 9.63 * SS_NBR_PURCHASED
    WHERE SALE_ID = '10001';
    
UPDATE SALES_DETAIL
  SET LINE_TOTAL = 7.43 * SS_NBR_PURCHASED
    WHERE SALE_ID = '10002';
    
    
SELECT DISTINCT AUTHORS.LAST_NAME AS "Last Name", AUTHORS.FIRST_NAME AS "First Name",
        BOOKS.TITLE AS "Title", BOOKS.CATEGORY AS "Category", BOOKS.PRICE AS "Price",
        BOOKS.PAPERBACK AS "Paperback", PUBLISHERS.NAME AS "Name",PUBLISHERS.CITY AS "City",
        PUBLISHERS.STATE AS "State"
        FROM AUTHORS, BOOKS, BOOKS_AUTHORS , PUBLISHERS
        WHERE (BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID) AND (BOOKS_AUTHORS.BOOK_CODE = BOOKS.B_CODE)
              AND (BOOKS.PUBLISHER_CODE = PUBLISHERS.CODE)
        ORDER BY AUTHORS.LAST_NAME;
		
		
SELECT  BRANCHES.NAME AS "Name", BRANCHES.LOCATION AS "Location",
                BOOKS.CATEGORY AS "Category", BOOKS.TITLE AS "Title",
                BOOKS_BRANCHES.ON_HAND AS "On Hand",
                BOOKS_BRANCHES.REORDER_LEVEL AS "Reorder Level"
          FROM BOOKS, BOOKS_BRANCHES, BRANCHES
          WHERE BOOKS.B_CODE = BOOKS_BRANCHES.B_CODE AND 
                BOOKS_BRANCHES.BRANCH = BRANCHES.BRANCH
           ORDER BY BRANCHES.NAME;
		   
		   
SELECT BOOKS.CATEGORY AS "Category", BOOKS.TITLE AS "Title",
        BOOKS.PRICE AS "Price", AUTHORS.LAST_NAME
    FROM BOOKS, BOOKS_AUTHORS, AUTHORS
    WHERE BOOKS_AUTHORS.BOOK_CODE = BOOKS.B_CODE AND
          BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID
    ORDER BY BOOKS.CATEGORY;
	
	
SELECT PUBLISHERS.NAME AS "Name", PUBLISHERS.CITY AS "City",
        PUBLISHERS.STATE AS "State", BOOKS.TITLE AS "Title",
        BOOKS.PAPERBACK AS "Paperback"
      FROM BOOKS,PUBLISHERS
      WHERE BOOKS.PUBLISHER_CODE = PUBLISHERS.CODE
      ORDER BY PUBLISHERS.NAME,BOOKS.TITLE;
	  


SELECT DISTINCT AUTHORS.LAST_NAME AS "Last Name", AUTHORS.FIRST_NAME AS "First Name",
              BOOKS.TITLE AS "Title", BOOKS.PRICE AS "Price", SALES_RECEIPT.SALE_DATE AS "Sale Date",
              SALES_DETAIL.SS_NBR_PURCHASED AS "Number Sold"
          FROM AUTHORS, BOOKS, SALES_RECEIPT, SALES_DETAIL, BOOKS_AUTHORS
          WHERE BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID AND BOOKS_AUTHORS.BOOK_CODE = BOOKS.B_CODE
                AND BOOKS.B_CODE = SALES_DETAIL.B_CODE AND SALES_RECEIPT.SALE_ID = SALES_DETAIL.SALE_ID
          ORDER BY AUTHORS.LAST_NAME;

/* 9 */          
SELECT BOOKS.CATEGORY, BOOKS.PRICE, BOOKS.TITLE, AUTHORS.LAST_NAME, AUTHORS.FIRST_NAME
  FROM BOOKS, AUTHORS, BOOKS_AUTHORS
  WHERE BOOKS.CATEGORY = 'MYS'
  AND BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID
  ORDER BY AUTHORS.LAST_NAME;
  
 /* 10 */
 SELECT BOOKS.CATEGORY, BOOKS.PRICE, BOOKS.TITLE, AUTHORS.LAST_NAME, AUTHORS.FIRST_NAME
  FROM BOOKS, AUTHORS, BOOKS_AUTHORS
  WHERE BOOKS.B_CODE = BOOKS_AUTHORS.BOOK_CODE
  AND BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID
  ORDER BY AUTHORS.LAST_NAME;
  
 
 SELECT BOOKS.CATEGORY, COUNT(DISTINCT BOOKS.TITLE)
  FROM BOOKS
    GROUP BY BOOKS.CATEGORY;
    
/* 11 */
UPDATE SALES_RECEIPT
  SET SALES_RECEIPT.CUST_ID = '10001'
  WHERE SALES_RECEIPT.SALE_ID = '10000';
  
  UPDATE SALES_RECEIPT
  SET SALES_RECEIPT.CUST_ID = '10002'
  WHERE SALES_RECEIPT.SALE_ID = '10001';
  
  UPDATE SALES_RECEIPT
  SET SALES_RECEIPT.CUST_ID = '10003'
  WHERE SALES_RECEIPT.SALE_ID = '10002';
  
  
  SELECT DISTINCT CUSTOMER.CUST_ID, SALES_RECEIPT.SALE_DATE, BOOKS.TITLE,
              SALES_DETAIL.SS_NBR_PURCHASED, SALES_DETAIL.LINE_TOTAL
          FROM BOOKS, SALES_DETAIL, SALES_RECEIPT, CUSTOMER
          WHERE CUSTOMER.CUST_ID = SALES_RECEIPT.CUST_ID
                AND BOOKS.B_CODE = SALES_DETAIL.B_CODE AND 
                SALES_RECEIPT.SALE_ID = SALES_DETAIL.SALE_ID
          ORDER BY CUSTOMER.CUST_ID;
  /* 12 */
  CREATE VIEW NUMBER12 AS
SELECT DISTINCT CUSTOMER.CUST_ID, SALES_RECEIPT.SALE_DATE, BOOKS.TITLE,
              SALES_DETAIL.SS_NBR_PURCHASED, SALES_DETAIL.LINE_TOTAL
          FROM BOOKS, SALES_DETAIL, SALES_RECEIPT, CUSTOMER
          WHERE CUSTOMER.CUST_ID = SALES_RECEIPT.CUST_ID
                AND BOOKS.B_CODE = SALES_DETAIL.B_CODE AND 
                SALES_RECEIPT.SALE_ID = SALES_DETAIL.SALE_ID
          ORDER BY CUSTOMER.CUST_ID;
/*13*/
SELECT *
  FROM NUMBER12
  WHERE  NUMBER12.CUST_ID = '10003';

/* 14*/

SELECT AVG(NUMBER12.LINE_TOTAL)
  FROM NUMBER12;
          
SELECT MIN(NUMBER12.LINE_TOTAL)
  FROM NUMBER12;
          
          
SELECT MAX(NUMBER12.LINE_TOTAL)
  FROM NUMBER12;
  
/*15*/
CREATE VIEW NUMBER14 AS
SELECT BRANCHES.NAME, BOOKS.TITLE, BOOKS.PRICE, BOOKS_BRANCHES.ON_HAND
  FROM BOOKS_BRANCHES, BRANCHES, BOOKS
  WHERE BOOKS.B_CODE = BOOKS_BRANCHES.B_CODE 
  AND BOOKS_BRANCHES.BRANCH = BRANCHES.BRANCH
  ORDER BY BRANCHES.BRANCH;
  
/*16*/
SELECT SUM(BOOKS.PRICE)
  FROM BOOK;
  
  
 /* 17*/
  
SELECT NUMBER14.NAME, COUNT(NUMBER14.ON_HAND), AVG(ON_HAND)
  FROM NUMBER14
    GROUP BY NUMBER14.NAME
    ORDER BY NUMBER14.NAME DESC;
	
	
/*18*/
SELECT NUMBER14.NAME, AVG(ON_HAND)
  FROM NUMBER14
  WHERE ON_HAND > (SELECT AVG(ON_HAND) FROM NUMBER14)
  GROUP BY NAME
    ORDER BY NUMBER14.NAME;